---
- name: IP Address
  hosts: localhost
  become: yes
  gather_facts: false
  vars_files:
    - files.yml
  tasks:
    - name: create a dir
      file:
        path: /opt/ipdir
        state: directory
        
    - name: Copy IP address
      copy:
        dest: "/opt/ipdr/{{ item }}.ip"
        content: "IPADDR={{lookup('file',item)|regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')|unique|join(',')|default(‘none’,true)}}"
      loop: "{{ files }}"
      
